Updates
RWTH-EBC/MoCITempGen pull request #13
Opened 2023-10-09 22:46 UTC by DaJansenGit

* improves usage of pathlib (still some work to do)
* improves docs

2023-10-09 23:32 UTC, FWuellhorst requested changes
Minor first comments

2023-10-09 23:32 UTC, FWuellhorst commented on CI_templates_python/README.md
> +Execute the `python python CI_templates_python/ci_templates.py` command in the root directory of your repository.
Duplicate python

2023-10-09 23:32 UTC, FWuellhorst commented on CI_templates_python/README.md
> +Then the command `python python CI_templates_python/ci_templates.py --setting` must be executed.
Same here

2023-10-10 06:52 UTC, DaJansenGit commented on CI_templates_python/README.md
> +Execute the `python python CI_templates_python/ci_templates.py` command in the root directory of your repository.
fixed

2023-10-10 06:52 UTC, DaJansenGit commented on CI_templates_python/README.md
> +Then the command `python python CI_templates_python/ci_templates.py --setting` must be executed.
fixed

2023-10-10 07:17 UTC, FWuellhorst requested changes
Minot requests, looks good aside from that :)

2023-10-10 07:17 UTC, FWuellhorst commented on CITests/CleanUp/structure_check.py
>  sys.path.append('Dymola_python_tests/CITests/CI_Configuration')
Shouldn't this be fixed now?

2023-10-10 07:17 UTC, FWuellhorst commented on README.md
> +not only GitLab repos can use MoCITempGen generated templates buy any GitHub,
buy -> but

2023-10-10 07:17 UTC, FWuellhorst commented on CI_templates_python/ci_templates.py
> +        yml_file = (ci_folder / self.temp_ci_structure_file.stem).with_suffix('.yml')
/ is not always save i think, use `.joinpath`  instead.

2023-10-11 08:15 UTC, merged